vim.o.number = true
vim.o.relativenumber = true
vim.o.ruler = true
vim.o.scrolloff = 8
vim.o.tabstop = 4
vim.o.shiftwidth=4
vim.o.expandtab = true
vim.o.termguicolors = true
vim.o.softtabstop = 4
vim.o.sidescrolloff = 5
vim.o.signcolumn = "yes"
vim.o.smartcase = true
vim.o.smarttab = true
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.startofline = false
vim.g.mouse = true
vim.o.undodir = "/home/kevin/.cache/nvim/" .. "undo/"
vim.o.undofile = true
vim.o.swapfile = false
vim.o.showbreak = "↳  "
vim.o.cursorline = true
vim.o.clipboard = "unnamedplus"
vim.o.breakat = [[\ \	;:,!?]]
vim.o.autoindent = true
vim.o.autoread = true
vim.o.autowrite = true
vim.o.whichwrap = "h,l,<,>,[,],~"
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.opt.list = true
